server.host: 0.0.0.0

elasticsearch:
  hosts: [""]
  username: kibanaserver
  password: ***********
  requestHeadersWhitelist: ["securitytenant", "Authorization", "security_tenant"]

elasticsearch.ssl:
  certificate: "/usr/share/kibana/config/esnode.pem"
  key: "/usr/share/kibana/config/esnode-key.pem"
  certificateAuthorities: [ "/usr/share/kibana/config/root-ca.pem" ]
  verificationMode: none

# OpenDistro

opendistro_security:
  allow_client_certificates: true
  multitenancy.enabled: true
  #multitenancy.tenants.preferred: ["Private", "Global"]
  multitenancy.tenants.enable_global: false
  multitenancy.tenants.enable_private: false
  multitenancy.enable_filter: true
  readonly_mode.roles: ["kibana_read_only"]
  cookie.secure: false

logging:
  quiet: false
  verbose: true

# OpenId Connect
# Enable OpenID authentication
#opendistro_security.auth.type: "openid"

# The IdP metadata endpoint
#opendistro_security.openid.connect_url: "https://openid/.well-known/openid-configuration"

# The ID of the OpenID Connect client in your IdP
#opendistro_security.openid.client_id: "kibana-sso"

#opendistro_security.openid.scope: "openid profile"

#opendistro_security.openid.base_redirect_url: https://domain.cloud
